site_name: SinPatinhas — Análise de Requisitos
repo_name: 2025.2-SinPatinhas
repo_url: "https://github.com/Requisitos-de-Software/2025.2-SinPatinhas"          

theme:
  name: material
  language: pt
  logo: docs/assets/images/sinpatinhas_logo.png
  favicon: docs/assets/images/sinpatinhas_logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.expand
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light"
      scheme: default
      primary: cyan
      accent: blue
      toggle:
        icon: material/weather-night
        name: Modo escuro
    - media: "(prefers-color-scheme: dark"
      scheme: slate
      primary: cyan
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Modo claro

plugins:
  - search
  - git-revision-date-localized:
      type: date
      locale: pt_BR
      fallback_to_build_date: true

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - styles/overrides.css

nav:
  - Tela inicial: index.md
  - Planejamento:
    - Visão geral: planejamento/index.md
    - Aplicativo analisado: planejamento/aplicativo/index.md
    - Atas de reuniões: planejamento/atas/index.md
    - Ata 1: planejamento/atas/ata_reuniao_1.md
    - Ata 2: planejamento/atas/ata_reuniao_2.md
    - Ata 3: planejamento/atas/ata_reuniao_3.md
    - Cronograma da equipe: planejamento/cronograma/index.md
    - Ferramentas: planejamento/ferramentas/index.md
    - Heatmap da equipe: planejamento/heatmap/index.md
    - Metodologias: planejamento/metodologias/index.md
    - Referências: planejamento/referencias/index.md
    - Rich Picture: planejamento/rich-picture/index.md
  - Elicitação de Requisitos:
    - Visão geral: elicitacao/index.md
  - Modelagem:
    - Cenários: modelagem/cenarios.md
    - Léxicos: modelagem/lexicos.md
    - Casos de Uso: modelagem/casos_de_uso.md
    - Especificação Suplementar: modelagem/especificacao_suplementar.md
  - Agiligade:
    - Histórias de Usuário: agilidade/historias_de_usuario.md
    - Backlog: agilidade/backlog.md
    - NFR Framework: agilidade/nfr_framework.md
  - Análise:
    - Verificação: analise/verif_principal.md
    - Validação: analise/valid_principal.md
  - Pós-Rastreabilidade:
    - Forward-From: pos-rastreabilidade/foward_from.md
    - Backward-From: pos-rastreabilidade/backward_from.md
    - Matriz Geral: pos-rastreabilidade/matriz_geral.md
